### ISSUE TITLE
LICENSEファイルの作成

### ISSUE THREAD

**Issue by shigeonakane** [daishir0/Papernote#2]
READMEを呼んでいたところ、ライセンスについては、**「LICENSEファイルをご覧ください」**と記載されていますが
どうやら見当たらないみたいです。
作成が必要そうですね。 
@daishir0

**Comment by daishir0** [comment]
ほんとですね！対処します！

**Comment by daishir0** [comment]
アサインをしました

**Comment by daishir0** [comment]
https://github.com/daishir0/Papernote/commit/6b09ea43c7febbc7bcedc085004a44404f7d2e4d
で対応しました。完了としますね。
